### ISSUE TITLE
no page found 'configure-entries.jelly' for class ComputeEngineInstance

### ISSUE THREAD

**Issue by francisdb** [jenkinsci/google-compute-engine-plugin#159] opened 2019-11-06 08:40 UTC
Jenkins 2.203
Google Compute Engine Plugin 4.1.1

When trying to add a node in the nodes management after selecting `Google Compute Engine`, giving a name and clicking OK I get the following stacktrace:

> org.apache.commons.jelly.JellyTagException: jar:file:/var/cache/jenkins/war/WEB-INF/lib/jenkins-core-2.203.jar!/hudson/model/ComputerSet/_new.jelly:41:95: <st:include> No page found 'configure-entries.jelly' for class com.google.jenkins.plugins.computeengine.ComputeEngineInstance

**Comment by stephenashank** [comment] 2019-11-06 18:24
Hi @francisdb. This is a duplicate of #39. To briefly recap, with the way that instances are currently configured and provisioned, we provide a read-only view for ComputeEngineInstance. In order to provision nodes manually, you first need to make a cloud and configuration through the "Configure System" link on the "Manage Jenkins" page, or "<your jenkins url>/configure". Then on the build executor status page or "<your jenkins url>/computer", you should see a drop down with "Provision via <label>". Choose the description for the configuration that you want to use from that dropdown and it will manually provision a node.

Currently we don't have plans to change this.

**Closed** 2019-11-06 18:27 UTC
Labels: wontfix
