### ISSUE TITLE
support oslogin

### ISSUE THREAD

**Issue by flokli** [jenkinsci/google-compute-engine-plugin#141] opened 2019-09-04 22:45 UTC
Currently, starting instances requires creating an ssh keypair, adding the pubkey to the projects metadata, and baking it into the image.

There's images available which support oslogin just fine.

It would be very convenient if this plugin would also support using oslogin for ssh access, and then su(do) to the specified user.

**Comment by craigdbarber** [comment] 2019-09-05 20:09
Duplicate of: https://github.com/jenkinsci/google-compute-engine-plugin/issues/138

**Closed by craigdbarber** 2019-09-05 20:09 UTC
